artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion #create a directory in artifacts by the name data_ingestion
  dataset_name: jessemostipak/hotel-booking-demand #dataset from kaggle api token key downloaded dataset
  local_data_file: artifacts/data_ingestion/hotel-booking-demand.zip #downloading in compessed format to the place where the local_data_file specifies
  unzip_dir: artifacts/data_ingestion #extracting the data from the compressed folder to feed to the model

data_validation:
   root_dir: artifacts/data_ingestion #create a directory in artifacts by the name data_ingestion
   STATUS_FILE: artifacts/data_validation/status.txt
   unzip_data_dir: artifacts/data_ingestion/hotel_bookings.csv
   all_schema: schema.yaml


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/hotel_bookings.csv
  transformed_train_path: artifacts/data_transformation/train.csv  # scale train path
  transformed_test_path: artifacts/data_transformation/test.csv    # scaled test path
  transformed_unscaled_train_path: artifacts/data_transformation/train_unscaled.csv
  transformed_unscaled_test_path: artifacts/data_transformation/test_unscaled.csv
  preprocessor_scaled_path: artifacts/data_transformation/preprocessor_scaled.pkl
  preprocessor_unscaled_path: artifacts/data_transformation/preprocessor_unscaled.pkl
  

     